
services:
  postgres:
    image: postgres:latest
    container_name: postgresFlowX
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 4427
      POSTGRES_DB: flow_x
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redisFlowX
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  minio:
    image: minio/minio
    container_name: minioFlowX
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: 44444427
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  redis_data:
  minio_data:

